on:
  push:
    branches:
      - main
  pull_request:

jobs:
  linting:
    name: Check linting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        make install dev=true

    - name: Check linting
      run: |
        make lint
